#!/bin/bash

# CLI 询问重复问题调试脚本

echo "==================================================================="
echo "CLI 询问重复问题调试"
echo "==================================================================="

echo ""
echo "1. 检查日志中的 CLI 询问事件"
echo "-------------------------------------------------------------------"
echo "请在 VSCode 开发者工具控制台中查找以下日志："
echo ""
echo "  [WebviewProvider] 收到 CLI 询问事件:"
echo ""
echo "检查点："
echo "  - questionId 是否每次都不同？"
echo "  - content 是否为空？"
echo "  - 是否有多个相同的询问？"

echo ""
echo "2. 检查前端控制台日志"
echo "-------------------------------------------------------------------"
echo "在浏览器开发者工具中查找："
echo ""
echo "  [Webview] 收到 CLI 询问:"
echo ""
echo "检查点："
echo "  - 是否收到了多次相同的询问？"
echo "  - questionId 是否相同？"
echo "  - content 内容是什么？"

echo ""
echo "3. 可能的原因"
echo "-------------------------------------------------------------------"
echo "原因 1: CLI 输出了多次询问文本"
echo "  - 解决：改进询问检测逻辑，避免重复检测"
echo ""
echo "原因 2: questionId 生成逻辑有问题"
echo "  - 当前：questionId = requestId-timestamp"
echo "  - 问题：每次检测都生成新 ID"
echo "  - 解决：基于询问内容生成稳定的 ID"
echo ""
echo "原因 3: 前端去重逻辑失效"
echo "  - 检查：findCliQuestionIndex 是否正确匹配"
echo "  - 检查：questionId 是否为 undefined"

echo ""
echo "4. 临时解决方案"
echo "-------------------------------------------------------------------"
echo "方案 1: 基于内容生成 questionId"
echo "  const contentHash = crypto.createHash('md5')"
echo "    .update(content).digest('hex').slice(0, 8);"
echo "  questionId = \`\${requestId}-\${contentHash}\`;"
echo ""
echo "方案 2: 添加询问去重检测"
echo "  if (this.lastQuestionContent === content) {"
echo "    return; // 跳过重复询问"
echo "  }"
echo ""
echo "方案 3: 前端增强去重"
echo "  // 不仅匹配 questionId，还匹配 content"
echo "  const exists = list.find(m => "
echo "    m.type === 'cli_question' && "
echo "    (m.questionId === questionId || m.content === content)"
echo "  );"

echo ""
echo "5. 调试命令"
echo "-------------------------------------------------------------------"
echo "# 查看最近的 CLI 询问日志"
echo "grep 'CLI 询问' ~/.vscode/extensions/*/logs/*.log | tail -20"
echo ""
echo "# 查看 questionId 分布"
echo "grep 'questionId' ~/.vscode/extensions/*/logs/*.log | tail -20"

echo ""
echo "==================================================================="
echo "请按照以上步骤检查，并提供以下信息："
echo "1. 日志中的 questionId 是否相同？"
echo "2. content 内容是什么？"
echo "3. 是否有多次相同的询问事件？"
echo "==================================================================="
