// @generated by scripts/generate-app-server-protocol.mjs from contracts/app-server/app-server.schema.json.
// DO NOT EDIT. Change the schema and rerun: npm run protocol:generate

use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const PROTOCOL_NAME: &str = "magi.app-server";
pub const PROTOCOL_MAJOR: u16 = 1;
pub const PROTOCOL_MINOR: u16 = 0;
pub const JSONRPC_VERSION: &str = "2.0";
pub const APP_SERVER_METHODS: &[&str] = &[
    "initialize",
    "initialized",
    "ping",
    "session/list",
    "session/read",
    "turn/start",
    "events/subscribe",
    "browser/tools/list",
    "browser/tool",
    "approval/request",
    "$/cancelRequest",
];

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AppServerMethodKind {
    Request,
    Notification,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AppServerMethodSignature {
    pub method: &'static str,
    pub kind: AppServerMethodKind,
    pub params: &'static str,
    pub result: Option<&'static str>,
    pub server_request: bool,
}

pub const APP_SERVER_METHOD_SIGNATURES: &[AppServerMethodSignature] = &[
    AppServerMethodSignature {
        method: "initialize",
        kind: AppServerMethodKind::Request,
        params: "InitializeParams",
        result: Some("InitializeResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "initialized",
        kind: AppServerMethodKind::Notification,
        params: "EmptyParams",
        result: None,
        server_request: false,
    },
    AppServerMethodSignature {
        method: "ping",
        kind: AppServerMethodKind::Request,
        params: "EmptyParams",
        result: Some("PingResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "session/list",
        kind: AppServerMethodKind::Request,
        params: "SessionListParams",
        result: Some("SessionListResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "session/read",
        kind: AppServerMethodKind::Request,
        params: "SessionReadParams",
        result: Some("SessionReadResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "turn/start",
        kind: AppServerMethodKind::Request,
        params: "TurnStartParams",
        result: Some("TurnStartResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "events/subscribe",
        kind: AppServerMethodKind::Request,
        params: "EventSubscribeParams",
        result: Some("EventSubscribeResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "browser/tools/list",
        kind: AppServerMethodKind::Request,
        params: "BrowserToolsListParams",
        result: Some("BrowserToolsListResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "browser/tool",
        kind: AppServerMethodKind::Request,
        params: "BrowserToolParams",
        result: Some("BrowserToolResult"),
        server_request: false,
    },
    AppServerMethodSignature {
        method: "approval/request",
        kind: AppServerMethodKind::Request,
        params: "ApprovalRequestParams",
        result: Some("ApprovalDecision"),
        server_request: true,
    },
    AppServerMethodSignature {
        method: "$/cancelRequest",
        kind: AppServerMethodKind::Notification,
        params: "CancelRequestParams",
        result: None,
        server_request: false,
    },
];

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AppServerRequestMethod {
    Initialize,
    Ping,
    SessionList,
    SessionRead,
    TurnStart,
    EventsSubscribe,
    BrowserToolsList,
    BrowserTool,
    ApprovalRequest,
}

impl AppServerRequestMethod {
    pub const ALL: &[Self] = &[
        Self::Initialize,
        Self::Ping,
        Self::SessionList,
        Self::SessionRead,
        Self::TurnStart,
        Self::EventsSubscribe,
        Self::BrowserToolsList,
        Self::BrowserTool,
        Self::ApprovalRequest,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Initialize => "initialize",
            Self::Ping => "ping",
            Self::SessionList => "session/list",
            Self::SessionRead => "session/read",
            Self::TurnStart => "turn/start",
            Self::EventsSubscribe => "events/subscribe",
            Self::BrowserToolsList => "browser/tools/list",
            Self::BrowserTool => "browser/tool",
            Self::ApprovalRequest => "approval/request",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AppServerNotificationMethod {
    Initialized,
    CancelRequest,
}

impl AppServerNotificationMethod {
    pub const ALL: &[Self] = &[Self::Initialized, Self::CancelRequest];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Initialized => "initialized",
            Self::CancelRequest => "$/cancelRequest",
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AppServerRequestParams {
    Initialize(InitializeParams),
    Ping(EmptyParams),
    SessionList(SessionListParams),
    SessionRead(SessionReadParams),
    TurnStart(TurnStartParams),
    EventsSubscribe(EventSubscribeParams),
    BrowserToolsList(BrowserToolsListParams),
    BrowserTool(BrowserToolParams),
    ApprovalRequest(ApprovalRequestParams),
}

#[derive(Clone, Debug, PartialEq)]
pub enum AppServerNotificationParams {
    Initialized(EmptyParams),
    CancelRequest(CancelRequestParams),
}

#[allow(clippy::large_enum_variant)]
#[derive(Clone, Debug, PartialEq)]
pub enum AppServerResult {
    Initialize(InitializeResult),
    Ping(PingResult),
    SessionList(SessionListResult),
    SessionRead(SessionReadResult),
    TurnStart(TurnStartResult),
    EventsSubscribe(EventSubscribeResult),
    BrowserToolsList(BrowserToolsListResult),
    BrowserTool(BrowserToolResult),
    ApprovalRequest(ApprovalDecision),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum JsonRpcVersion {
    #[serde(rename = "2.0")]
    V2,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum RequestId {
    String(String),
    Number(String),
}

impl RequestId {
    pub fn new(value: impl Into<String>) -> Result<Self, crate::ProtocolError> {
        let value = value.into();
        if value.trim().is_empty() {
            return Err(crate::ProtocolError::InvalidRequest(
                "request id 不能为空".to_string(),
            ));
        }
        Ok(Self::String(value))
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::String(value) | Self::Number(value) => value,
        }
    }
}

impl Serialize for RequestId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Self::String(value) => serializer.serialize_str(value),
            Self::Number(value) => value
                .parse::<serde_json::Number>()
                .map_err(|_| serde::ser::Error::custom("request id 数字无法序列化"))?
                .serialize(serializer),
        }
    }
}

impl<'de> Deserialize<'de> for RequestId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        match Value::deserialize(deserializer)? {
            Value::String(value) => Self::new(value).map_err(serde::de::Error::custom),
            Value::Number(value) => Ok(Self::Number(value.to_string())),
            _ => Err(serde::de::Error::custom("request id 必须是字符串或数字")),
        }
    }
}

pub type JsonRpcRequestId = RequestId;

pub type JsonValue = Value;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProtocolVersion {
    pub major: u16,
    pub minor: u16,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ClientInfo {
    pub name: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ClientCapabilities {
    #[serde(default)]
    #[serde(rename = "desktopBrowserSurface")]
    pub desktop_browser_surface: bool,
    #[serde(default)]
    #[serde(rename = "browserTools")]
    pub browser_tools: bool,
    #[serde(default)]
    pub approvals: bool,
    #[serde(default)]
    pub streaming: bool,
    #[serde(default)]
    #[serde(rename = "optOutNotificationMethods")]
    pub opt_out_notification_methods: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EmptyParams {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PingResult {
    #[serde(rename = "runtimeEpoch")]
    pub runtime_epoch: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ServerCapabilities {
    pub sessions: bool,
    pub turns: bool,
    pub events: bool,
    pub approvals: bool,
    #[serde(rename = "browserTools")]
    pub browser_tools: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct InitializeParams {
    #[serde(rename = "clientInfo")]
    pub client_info: ClientInfo,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocol: Option<ProtocolVersion>,
    #[serde(default)]
    pub capabilities: ClientCapabilities,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct InitializeResult {
    #[serde(rename = "serverInfo")]
    pub server_info: ClientInfo,
    pub protocol: ProtocolVersion,
    #[serde(rename = "runtimeEpoch")]
    pub runtime_epoch: String,
    pub capabilities: ServerCapabilities,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserToolsListParams {
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "sessionId")]
    pub session_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventSubscribeParams {
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "sessionId")]
    pub session_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workspaceId")]
    pub workspace_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "afterSequence")]
    pub after_sequence: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionListParams {
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workspaceId")]
    pub workspace_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionReadParams {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(default)]
    #[serde(rename = "includeTurns")]
    pub include_turns: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SessionScope {
    #[serde(rename = "personal")]
    Personal,
    #[serde(rename = "workspace")]
    Workspace,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionTurnImage {
    pub name: String,
    #[serde(rename = "dataUrl")]
    pub data_url: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SessionContextReferenceKind {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "directory")]
    Directory,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionContextReference {
    pub kind: SessionContextReferenceKind,
    pub path: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "pathRef")]
    pub path_ref: Option<String>,
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum AccessProfile {
    #[serde(rename = "read_only")]
    ReadOnly,
    #[serde(rename = "restricted")]
    Restricted,
    #[serde(rename = "full_access")]
    FullAccess,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TurnStartParams {
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "sessionId")]
    pub session_id: Option<String>,
    pub scope: SessionScope,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workspaceId")]
    pub workspace_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workspacePath")]
    pub workspace_path: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "skillName")]
    pub skill_name: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(default)]
    #[serde(rename = "goalMode")]
    pub goal_mode: bool,
    #[serde(default)]
    pub images: Vec<SessionTurnImage>,
    #[serde(default)]
    #[serde(rename = "contextReferences")]
    pub context_references: Vec<SessionContextReference>,
    #[serde(default)]
    #[serde(rename = "browserAnnotationRefs")]
    pub browser_annotation_refs: Vec<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "accessProfile")]
    pub access_profile: Option<AccessProfile>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "orchestratorSessionConfig")]
    pub orchestrator_session_config: Option<Value>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "requestId")]
    pub request_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "userMessageId")]
    pub user_message_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "placeholderMessageId")]
    pub placeholder_message_id: Option<String>,
    #[serde(default)]
    #[serde(rename = "steerCurrentTurn")]
    pub steer_current_turn: bool,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "expectedTurnId")]
    pub expected_turn_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "replaceTurnId")]
    pub replace_turn_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionSummary {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: Option<String>,
    pub title: String,
    pub status: String,
    #[serde(rename = "createdAt")]
    pub created_at: u64,
    #[serde(rename = "updatedAt")]
    pub updated_at: u64,
    #[serde(rename = "messageCount")]
    pub message_count: usize,
    #[serde(rename = "isRunning")]
    pub is_running: bool,
    #[serde(rename = "runningTaskCount")]
    pub running_task_count: usize,
    #[serde(rename = "hasUnreadCompletion")]
    pub has_unread_completion: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionListResult {
    pub sessions: Vec<SessionSummary>,
    #[serde(rename = "runtimeEpoch")]
    pub runtime_epoch: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionReadResult {
    pub session: SessionSummary,
    pub turns: Vec<CanonicalTurn>,
    #[serde(rename = "runtimeEpoch")]
    pub runtime_epoch: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum EventCategory {
    #[serde(rename = "Domain")]
    Domain,
    #[serde(rename = "Audit")]
    Audit,
    #[serde(rename = "Usage")]
    Usage,
    #[serde(rename = "Projection")]
    Projection,
    #[serde(rename = "System")]
    System,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CanonicalTurnStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CanonicalTurnItemKind {
    #[serde(rename = "user_message")]
    UserMessage,
    #[serde(rename = "assistant_text")]
    AssistantText,
    #[serde(rename = "assistant_thinking")]
    AssistantThinking,
    #[serde(rename = "tool_call")]
    ToolCall,
    #[serde(rename = "task_status")]
    TaskStatus,
    #[serde(rename = "system_notice")]
    SystemNotice,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CanonicalTurnItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CanonicalTurnEventKind {
    #[serde(rename = "turn_started")]
    TurnStarted,
    #[serde(rename = "turn_item_upsert")]
    TurnItemUpsert,
    #[serde(rename = "turn_completed")]
    TurnCompleted,
    #[serde(rename = "turn_superseded")]
    TurnSuperseded,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CanonicalTurnVisibility {
    #[serde(default)]
    pub renderable: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CanonicalToolCall {
    #[serde(rename = "callId")]
    pub call_id: String,
    pub name: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Value>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<Value>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CanonicalWorkerRef {
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "taskId")]
    pub task_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workerId")]
    pub worker_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "roleId")]
    pub role_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CanonicalTurnItem {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "turnId")]
    pub turn_id: String,
    #[serde(rename = "turnSeq")]
    pub turn_seq: u64,
    #[serde(rename = "itemId")]
    pub item_id: String,
    #[serde(rename = "itemSeq")]
    pub item_seq: usize,
    pub kind: CanonicalTurnItemKind,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    pub status: CanonicalTurnItemStatus,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "itemVersion")]
    pub item_version: Option<u64>,
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default)]
    pub blocks: Vec<Value>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool: Option<CanonicalToolCall>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worker: Option<CanonicalWorkerRef>,
    #[serde(rename = "sourceThreadId")]
    pub source_thread_id: String,
    #[serde(default)]
    pub visibility: CanonicalTurnVisibility,
    #[serde(default)]
    pub metadata: std::collections::HashMap<String, Value>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CanonicalTurn {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "turnId")]
    pub turn_id: String,
    #[serde(rename = "turnSeq")]
    pub turn_seq: u64,
    #[serde(rename = "acceptedAt")]
    pub accepted_at: i64,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "completedAt")]
    pub completed_at: Option<i64>,
    pub status: CanonicalTurnStatus,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "responseDurationMs")]
    pub response_duration_ms: Option<u64>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Value>,
    #[serde(default)]
    pub items: Vec<CanonicalTurnItem>,
    #[serde(default)]
    pub metadata: std::collections::HashMap<String, Value>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CanonicalTurnEvent {
    #[serde(rename = "canonicalSchemaVersion")]
    pub canonical_schema_version: String,
    #[serde(rename = "canonicalEventKind")]
    pub canonical_event_kind: CanonicalTurnEventKind,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "canonicalTurn")]
    pub canonical_turn: Option<CanonicalTurn>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "canonicalItem")]
    pub canonical_item: Option<CanonicalTurnItem>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TurnStartKind {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "queued")]
    Queued,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TurnStartRoute {
    #[serde(rename = "chat")]
    Chat,
    #[serde(rename = "execute")]
    Execute,
    #[serde(rename = "task")]
    Task,
    #[serde(rename = "continue")]
    Continue,
    #[serde(rename = "steer")]
    Steer,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TurnQueueInfo {
    #[serde(rename = "queueId")]
    pub queue_id: String,
    #[serde(rename = "queuePosition")]
    pub queue_position: usize,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TurnStartResult {
    pub kind: TurnStartKind,
    pub replayed: bool,
    #[serde(rename = "requestId")]
    pub request_id: Option<String>,
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "turnId")]
    pub turn_id: Option<String>,
    #[serde(rename = "entryId")]
    pub entry_id: String,
    #[serde(rename = "eventId")]
    pub event_id: String,
    #[serde(rename = "acceptedAt")]
    pub accepted_at: i64,
    #[serde(rename = "runtimeEpoch")]
    pub runtime_epoch: String,
    #[serde(rename = "eventStreamNextSequence")]
    pub event_stream_next_sequence: u64,
    #[serde(rename = "createdSession")]
    pub created_session: bool,
    pub route: Option<TurnStartRoute>,
    #[serde(rename = "sessionSummary")]
    pub session_summary: Option<SessionSummary>,
    #[serde(rename = "userMessageItemId")]
    pub user_message_item_id: Option<String>,
    #[serde(rename = "canonicalTurn")]
    pub canonical_turn: Option<CanonicalTurn>,
    #[serde(rename = "canonicalItem")]
    pub canonical_item: Option<CanonicalTurnItem>,
    pub queue: Option<TurnQueueInfo>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "rootTaskId")]
    pub root_task_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "actionTaskId")]
    pub action_task_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "executionChainRef")]
    pub execution_chain_ref: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "steeredTurnId")]
    pub steered_turn_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "canonicalSchemaVersion")]
    pub canonical_schema_version: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "canonicalEventKind")]
    pub canonical_event_kind: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventEnvelope {
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "event_type")]
    pub event_type: String,
    pub category: EventCategory,
    #[serde(rename = "occurred_at")]
    pub occurred_at: i64,
    pub sequence: u64,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workspace_id")]
    pub workspace_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "session_id")]
    pub session_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "mission_id")]
    pub mission_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "assignment_id")]
    pub assignment_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "task_id")]
    pub task_id: Option<String>,
    pub payload: Value,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventStreamSnapshot {
    #[serde(rename = "next_sequence")]
    pub next_sequence: u64,
    #[serde(rename = "recent_events")]
    pub recent_events: Vec<EventEnvelope>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventNotificationParams {
    pub sequence: u64,
    pub event: EventEnvelope,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventSubscribeResult {
    pub subscribed: bool,
    #[serde(rename = "nextSequence")]
    pub next_sequence: u64,
    #[serde(rename = "resyncRequired")]
    pub resync_required: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventSnapshotParams {
    #[serde(rename = "nextSequence")]
    pub next_sequence: u64,
    #[serde(rename = "recentEvents")]
    pub recent_events: Vec<EventEnvelope>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum EventResyncReason {
    #[serde(rename = "afterSequenceExpired")]
    AfterSequenceExpired,
    #[serde(rename = "clientTooSlow")]
    ClientTooSlow,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventResyncRequiredParams {
    pub reason: EventResyncReason,
    #[serde(rename = "requestedAfterSequence")]
    pub requested_after_sequence: Option<u64>,
    pub skipped: Option<u64>,
    pub snapshot: EventStreamSnapshot,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum BrowserAccessProfile {
    #[serde(rename = "read_only")]
    ReadOnly,
    #[serde(rename = "restricted")]
    Restricted,
    #[serde(rename = "full_access")]
    FullAccess,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum BrowserToolAccess {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "mixed")]
    Mixed,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserToolDescriptor {
    pub name: String,
    pub access: BrowserToolAccess,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum BrowserHostStatus {
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "starting")]
    Starting,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "reconnecting")]
    Reconnecting,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserCapabilitySnapshot {
    pub revision: u64,
    #[serde(rename = "inAppBrowserEnabled")]
    pub in_app_browser_enabled: bool,
    #[serde(rename = "browserUseEnabled")]
    pub browser_use_enabled: bool,
    #[serde(rename = "hostStatus")]
    pub host_status: BrowserHostStatus,
    #[serde(rename = "hostProtocolCompatible")]
    pub host_protocol_compatible: bool,
    #[serde(rename = "accessProfile")]
    pub access_profile: BrowserAccessProfile,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserToolsListResult {
    pub tools: Vec<BrowserToolDescriptor>,
    pub capabilities: BrowserCapabilitySnapshot,
    #[serde(rename = "runtimeEpoch")]
    pub runtime_epoch: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum BrowserToolResultStatus {
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "indeterminate")]
    Indeterminate,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserToolResult {
    pub tool: String,
    pub status: BrowserToolResultStatus,
    pub payload: Value,
    #[serde(rename = "itemId")]
    pub item_id: String,
    #[serde(rename = "turnId")]
    pub turn_id: String,
    #[serde(rename = "runtimeEpoch")]
    pub runtime_epoch: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserToolParams {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    pub tool: String,
    pub arguments: std::collections::HashMap<String, Value>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workspaceId")]
    pub workspace_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "callId")]
    pub call_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "accessProfile")]
    pub access_profile: Option<BrowserAccessProfile>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "browserCapabilityRevision")]
    pub browser_capability_revision: Option<u64>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "browserExecutionId")]
    pub browser_execution_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "taskId")]
    pub task_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workerId")]
    pub worker_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ApprovalRequestParams {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    pub reason: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub risk: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ApprovalDecision {
    pub approved: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ErrorObject {
    pub code: i32,
    pub message: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<JsonValue>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retryable: Option<bool>,
}
pub type JsonRpcError = ErrorObject;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct JsonRpcRequest {
    pub jsonrpc: Option<String>,
    pub id: RequestId,
    pub method: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "requestTimeoutMs")]
    pub request_timeout_ms: Option<u64>,
    #[serde(default)]
    pub params: Value,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct JsonRpcNotification {
    pub jsonrpc: Option<String>,
    pub method: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "requestTimeoutMs")]
    pub request_timeout_ms: Option<u64>,
    #[serde(default)]
    pub params: Value,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct JsonRpcResultResponse {
    pub jsonrpc: Option<String>,
    pub id: RequestId,
    pub result: JsonValue,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct JsonRpcErrorResponse {
    pub jsonrpc: Option<String>,
    pub id: RequestId,
    pub error: ErrorObject,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct JsonRpcResponse {
    pub jsonrpc: Option<String>,
    pub id: RequestId,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<JsonValue>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorObject>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CancelMethod {
    #[serde(rename = "$/cancelRequest")]
    CancelRequest,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CancelRequestParams {
    pub id: RequestId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CancelNotification {
    pub jsonrpc: JsonRpcVersion,
    pub method: CancelMethod,
    pub params: CancelRequestParams,
}

pub type JsonRpcServerRequest = JsonRpcRequest;

pub type JsonRpcServerNotification = JsonRpcNotification;

pub type JsonRpcServerResponse = JsonRpcResponse;

pub type ClientRequest = JsonRpcRequest;

pub type ClientNotification = JsonRpcNotification;

pub type ClientResponse = JsonRpcResponse;

pub type ServerRequest = JsonRpcServerRequest;

pub type ServerNotification = JsonRpcServerNotification;

pub type ServerResponse = JsonRpcServerResponse;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcMessage {
    Request(JsonRpcRequest),
    Notification(JsonRpcNotification),
    Variant3(JsonRpcResponse),
}
