// @generated by scripts/generate-browser-network-policy.mjs from contracts/desktop-browser/network-policy.json.
// DO NOT EDIT. Change the source and rerun: npm run browser-network-policy:generate

#[rustfmt::skip]
pub const BLOCKED_HOSTNAMES: &[&str] = &[
    "metadata.google.internal",
    "metadata.goog",
    "instance-data.ec2.internal",
];

#[rustfmt::skip]
pub const BLOCKED_CIDRS: &[&str] = &[
    "169.254.0.0/16",
    "100.100.100.200/32",
    "192.0.0.192/32",
    "fd00:ec2::254/128",
    "fe80::/10",
];

#[rustfmt::skip]
pub const LOOPBACK_HOSTNAMES: &[&str] = &[
    "localhost",
];

#[rustfmt::skip]
pub const LOOPBACK_CIDRS: &[&str] = &[
    "127.0.0.0/8",
    "0.0.0.0/8",
    "::1/128",
    "::/128",
];

#[rustfmt::skip]
pub const LAN_CIDRS: &[&str] = &[
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "100.64.0.0/10",
    "fc00::/7",
];

pub const PREVIEW_HOSTNAME: &str = "site.localhost";

pub const PREVIEW_PATH_PREFIX: &str = "/api/files/site/";

pub const PREVIEW_OPEN_PATH: &str = "/api/files/site-open";
