// @generated by scripts/generate-browser-tool-catalog.mjs from contracts/desktop-browser/browser-tool.schema.json.
// DO NOT EDIT. Change the schema and rerun: npm run browser-tool-catalog:generate

use serde::{Deserialize, Serialize};

pub const BROWSER_TOOL_CATALOG_SCHEMA_ID: &str =
    "https://magi.dev/contracts/browser-tool.schema.json";
pub const BROWSER_TOOL_CATALOG_SIZE: usize = 26;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrowserToolKind {
    Navigate,
    Snapshot,
    Click,
    Type,
    Press,
    Scroll,
    Screenshot,
    Tabs,
    Viewport,
    WaitFor,
    Hover,
    Drag,
    FillForm,
    Dialog,
    UploadFile,
    ClickAt,
    Evaluate,
    Console,
    Network,
    Emulate,
    Performance,
    Lighthouse,
    Heap,
    ThirdParty,
    WebMcp,
    Pwa,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrowserToolAccess {
    Read,
    Write,
    Mixed,
}

impl BrowserToolKind {
    pub const ALL: [Self; 26] = [
        Self::Navigate,
        Self::Snapshot,
        Self::Click,
        Self::Type,
        Self::Press,
        Self::Scroll,
        Self::Screenshot,
        Self::Tabs,
        Self::Viewport,
        Self::WaitFor,
        Self::Hover,
        Self::Drag,
        Self::FillForm,
        Self::Dialog,
        Self::UploadFile,
        Self::ClickAt,
        Self::Evaluate,
        Self::Console,
        Self::Network,
        Self::Emulate,
        Self::Performance,
        Self::Lighthouse,
        Self::Heap,
        Self::ThirdParty,
        Self::WebMcp,
        Self::Pwa,
    ];

    pub fn name(self) -> &'static str {
        match self {
            Self::Navigate => "browser_navigate",
            Self::Snapshot => "browser_snapshot",
            Self::Click => "browser_click",
            Self::Type => "browser_type",
            Self::Press => "browser_press",
            Self::Scroll => "browser_scroll",
            Self::Screenshot => "browser_screenshot",
            Self::Tabs => "browser_tabs",
            Self::Viewport => "browser_viewport",
            Self::WaitFor => "browser_wait_for",
            Self::Hover => "browser_hover",
            Self::Drag => "browser_drag",
            Self::FillForm => "browser_fill_form",
            Self::Dialog => "browser_dialog",
            Self::UploadFile => "browser_upload_file",
            Self::ClickAt => "browser_click_at",
            Self::Evaluate => "browser_evaluate",
            Self::Console => "browser_console",
            Self::Network => "browser_network",
            Self::Emulate => "browser_emulate",
            Self::Performance => "browser_performance",
            Self::Lighthouse => "browser_lighthouse",
            Self::Heap => "browser_heap",
            Self::ThirdParty => "browser_third_party",
            Self::WebMcp => "browser_webmcp",
            Self::Pwa => "browser_pwa",
        }
    }

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "browser_navigate" => Some(Self::Navigate),
            "browser_snapshot" => Some(Self::Snapshot),
            "browser_click" => Some(Self::Click),
            "browser_type" => Some(Self::Type),
            "browser_press" => Some(Self::Press),
            "browser_scroll" => Some(Self::Scroll),
            "browser_screenshot" => Some(Self::Screenshot),
            "browser_tabs" => Some(Self::Tabs),
            "browser_viewport" => Some(Self::Viewport),
            "browser_wait_for" => Some(Self::WaitFor),
            "browser_hover" => Some(Self::Hover),
            "browser_drag" => Some(Self::Drag),
            "browser_fill_form" => Some(Self::FillForm),
            "browser_dialog" => Some(Self::Dialog),
            "browser_upload_file" => Some(Self::UploadFile),
            "browser_click_at" => Some(Self::ClickAt),
            "browser_evaluate" => Some(Self::Evaluate),
            "browser_console" => Some(Self::Console),
            "browser_network" => Some(Self::Network),
            "browser_emulate" => Some(Self::Emulate),
            "browser_performance" => Some(Self::Performance),
            "browser_lighthouse" => Some(Self::Lighthouse),
            "browser_heap" => Some(Self::Heap),
            "browser_third_party" => Some(Self::ThirdParty),
            "browser_webmcp" => Some(Self::WebMcp),
            "browser_pwa" => Some(Self::Pwa),
            _ => None,
        }
    }

    pub fn catalog_access(self) -> BrowserToolAccess {
        match self {
            Self::Navigate => BrowserToolAccess::Write,
            Self::Snapshot => BrowserToolAccess::Read,
            Self::Click => BrowserToolAccess::Write,
            Self::Type => BrowserToolAccess::Write,
            Self::Press => BrowserToolAccess::Write,
            Self::Scroll => BrowserToolAccess::Write,
            Self::Screenshot => BrowserToolAccess::Read,
            Self::Tabs => BrowserToolAccess::Mixed,
            Self::Viewport => BrowserToolAccess::Mixed,
            Self::WaitFor => BrowserToolAccess::Read,
            Self::Hover => BrowserToolAccess::Write,
            Self::Drag => BrowserToolAccess::Write,
            Self::FillForm => BrowserToolAccess::Write,
            Self::Dialog => BrowserToolAccess::Mixed,
            Self::UploadFile => BrowserToolAccess::Write,
            Self::ClickAt => BrowserToolAccess::Write,
            Self::Evaluate => BrowserToolAccess::Write,
            Self::Console => BrowserToolAccess::Mixed,
            Self::Network => BrowserToolAccess::Mixed,
            Self::Emulate => BrowserToolAccess::Mixed,
            Self::Performance => BrowserToolAccess::Mixed,
            Self::Lighthouse => BrowserToolAccess::Mixed,
            Self::Heap => BrowserToolAccess::Mixed,
            Self::ThirdParty => BrowserToolAccess::Mixed,
            Self::WebMcp => BrowserToolAccess::Mixed,
            Self::Pwa => BrowserToolAccess::Read,
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::Navigate => "导航、后退、前进或刷新当前浏览器页面。",
            Self::Snapshot => "读取当前页面的可交互 DOM 与辅助功能快照。",
            Self::Click => "点击当前快照中的元素。",
            Self::Type => "向当前快照中的可编辑元素输入文本。",
            Self::Press => "向当前页面发送按键或组合键。",
            Self::Scroll => "滚动页面或指定快照元素。",
            Self::Screenshot => "截取当前视口、整页、指定元素或规范化区域。",
            Self::Tabs => {
                "列出、创建、激活或在用户明确要求时关闭 Magi 右栏的一级浏览器标签。每个一级浏览器标签只有一个 Chromium 页面；网页 popup、window.open 或 target=_blank 只在当前一级页面内导航，绝不创建网页子标签。"
            }
            Self::Viewport => "读取或通过 Chromium 原生设备指标设置页面视口。",
            Self::WaitFor => "等待文本、选择器或 URL 条件在当前页面满足。",
            Self::Hover => "将浏览器指针悬停到当前快照元素。",
            Self::Drag => "在同一快照版本中拖拽 source 元素至 target 元素。",
            Self::FillForm => "按当前快照引用批量填写表单字段。",
            Self::Dialog => "列出、接受、关闭或清理页面对话框。",
            Self::UploadFile => "向当前快照中的 file input 设置用户授权的文件。",
            Self::ClickAt => "在当前页面的 CSS 坐标点击或双击。",
            Self::Evaluate => "执行受控页面表达式并返回可序列化结果。",
            Self::Console => "读取、筛选、查看或清理控制台记录。",
            Self::Network => "读取、筛选、查看响应或清理网络记录。",
            Self::Emulate => "通过 Chromium DevTools 仿真网络、颜色、UA、地理位置等。",
            Self::Performance => "读取性能指标或控制性能追踪。",
            Self::Lighthouse => "复用当前真实 Browser Surface 执行 Lighthouse 审计。",
            Self::Heap => "读取堆和 DOM 计数，或生成并分析堆快照。",
            Self::ThirdParty => "统计、读取或清理第三方资源记录。",
            Self::WebMcp => "列出或调用页面暴露的 WebMCP 工具。",
            Self::Pwa => "读取当前页面的 PWA 条件和安装状态。",
        }
    }

    pub fn input_schema_json(self) -> &'static str {
        match self {
            Self::Navigate => {
                r#"{"type":"object","properties":{"action":{"type":"string","enum":["url","back","forward","stop","reload"],"description":"可选；提供 url 时默认执行 URL 导航，后退、前进或刷新时再显式填写"},"url":{"type":"string","minLength":1,"description":"要打开的 URL；提供该字段时 action 默认是 url"},"tab_id":{"type":"string","description":"可选；省略时使用活动标签页"},"ignore_cache":{"type":"boolean","description":"action=reload 时忽略缓存；默认 false"},"handle_before_unload":{"type":"string","enum":["accept","dismiss"],"description":"导航触发 beforeunload 时自动接受或取消"},"init_script":{"type":"string","description":"只对本次 URL 导航生效、在页面脚本前执行的 JavaScript"},"timeout_ms":{"type":"integer","minimum":1,"maximum":60000,"description":"导航超时，默认 15000 毫秒"},"include_snapshot":{"type":"boolean","description":"导航后还要继续交互时设为 true，在同一次工具结果中附带最新可访问性快照；默认 false"}},"required":[],"oneOf":[{"description":"URL 导航；action 可省略或必须为 url","required":["url"],"properties":{"action":{"enum":["url"]}},"not":{"required":["ignore_cache"]}},{"description":"停止当前页面的 Chromium 导航并保留当前已显示页面","required":["action"],"properties":{"action":{"enum":["stop"]}},"not":{"anyOf":[{"required":["url"]},{"required":["ignore_cache"]},{"required":["init_script"]}]}},{"description":"后退或前进","required":["action"],"properties":{"action":{"enum":["back","forward"]}},"not":{"anyOf":[{"required":["url"]},{"required":["ignore_cache"]},{"required":["init_script"]}]}},{"description":"刷新","required":["action"],"properties":{"action":{"enum":["reload"]}},"not":{"anyOf":[{"required":["url"]},{"required":["init_script"]}]}}]}"#
            }
            Self::Snapshot => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string","description":"可选；省略时使用活动标签页"}},"required":[]}"#
            }
            Self::Click => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string"},"include_snapshot":{"type":"boolean","description":"操作后附带最新可访问性快照；需要继续交互时设为 true，默认 false"}},"required":["snapshot_revision","element_ref"]}"#
            }
            Self::Type => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string"},"text":{"type":"string"},"replace":{"type":"boolean","description":"默认 true"},"submit_key":{"type":"string","description":"可选；输入后立即发送的按键，例如 Enter。搜索或表单提交应与输入合并，避免额外 browser_press 往返"},"include_snapshot":{"type":"boolean","description":"操作后附带最新可访问性快照；需要继续交互时设为 true，默认 false"}},"required":["snapshot_revision","element_ref","text"]}"#
            }
            Self::Press => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"key":{"type":"string","description":"按键或组合键，例如 Enter、Control+L"},"include_snapshot":{"type":"boolean","description":"操作后附带最新可访问性快照；需要继续交互时设为 true，默认 false"}},"required":["key"]}"#
            }
            Self::Scroll => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string","description":"可选；省略时滚动页面"},"delta_x":{"type":"number"},"delta_y":{"type":"number"},"include_snapshot":{"type":"boolean","description":"操作后附带最新可访问性快照；需要继续交互时设为 true，默认 false"}},"required":["delta_y"]}"#
            }
            Self::Screenshot => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string","description":"可选；省略时截取页面；与 clip、full_page 互斥"},"clip":{"type":"object","properties":{"x":{"type":"number","minimum":0,"maximum":1},"y":{"type":"number","minimum":0,"maximum":1},"width":{"type":"number","exclusiveMinimum":0,"maximum":1},"height":{"type":"number","exclusiveMinimum":0,"maximum":1}},"required":["x","y","width","height"],"description":"按当前视口归一化坐标截取区域；与 element_ref、full_page 互斥，只能三选一"},"format":{"type":"string","enum":["png","jpeg","webp"],"description":"图片格式，默认 png"},"quality":{"type":"integer","minimum":0,"maximum":100,"description":"jpeg/webp 压缩质量；format=png 时不要传此字段"},"full_page":{"type":"boolean","description":"设为 true 截取整页；不能同时传 element_ref 或 clip，默认 false"}},"required":[]}"#
            }
            Self::Tabs => {
                r#"{"type":"object","additionalProperties":false,"properties":{"action":{"type":"string","enum":["list","new","activate","close"],"description":"任务完成后不要使用 close；仅在用户明确要求关闭指定的 Magi 右栏一级标签时使用。网页 popup、window.open 或 target=_blank 不得通过此 action 创建子标签。"},"tab_id":{"type":"string","description":"activate/close 时必填，指向 Magi 右栏一级浏览器标签；不存在 parent_tab_id 或子标签身份"},"url":{"type":"string","description":"new 时可选；创建新的 Magi 右栏一级浏览器标签并立即打开 URL，省略时为 about:blank。不要为网页 popup 调用 new"}},"required":["action"]}"#
            }
            Self::Viewport => {
                r#"{"type":"object","properties":{"action":{"type":"string","enum":["get","set"]},"mode":{"type":"string","enum":["auto","fixed"],"description":"action=set 时必填；auto 跟随右侧内容槽，fixed 使用 width/height 进行 Chromium 响应式设备仿真。"},"tab_id":{"type":"string","description":"可选；省略时使用活动标签页"},"width":{"type":"integer","minimum":320,"maximum":7680,"description":"action=set 时必填"},"height":{"type":"integer","minimum":240,"maximum":4320,"description":"action=set 时必填"},"device_scale_factor_millis":{"type":"integer","minimum":500,"maximum":4000,"description":"action=set、mode=fixed 时可选，设备像素比乘以 1000，默认 1000。"},"device_type":{"type":"string","enum":["desktop","mobile"],"description":"action=set 时可选；宽度 320-600 固定为 mobile，601 以上固定为 desktop，传入值必须与 width 一致。mobile 启用手机窄屏仿真，desktop 表示电脑/平板宽屏。"}},"required":["action"],"oneOf":[{"description":"读取当前视口","properties":{"action":{"const":"get"}},"not":{"anyOf":[{"required":["mode"]},{"required":["width"]},{"required":["height"]},{"required":["device_scale_factor_millis"]},{"required":["device_type"]}]}},{"description":"恢复跟随右侧内容槽的自适应视口","properties":{"action":{"const":"set"},"mode":{"const":"auto"}},"required":["action","mode"],"not":{"anyOf":[{"required":["width"]},{"required":["height"]},{"required":["device_scale_factor_millis"]},{"required":["device_type"]}]}},{"description":"设置固定的 Chromium 响应式设备视口","properties":{"action":{"const":"set"},"mode":{"const":"fixed"}},"required":["action","mode","width","height"]}]}"#
            }
            Self::WaitFor => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"text":{"anyOf":[{"type":"string","minLength":1},{"type":"array","items":{"type":"string","minLength":1},"minItems":1}]},"texts":{"type":"array","items":{"type":"string","minLength":1},"minItems":1},"selector":{"type":"string","minLength":1},"url":{"type":"string","minLength":1},"timeout_ms":{"type":"integer","minimum":1,"maximum":60000}},"required":[],"anyOf":[{"required":["selector"]},{"required":["text"]},{"required":["texts"]},{"required":["url"]}]}"#
            }
            Self::Hover => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string"},"include_snapshot":{"type":"boolean"}},"required":["snapshot_revision","element_ref"]}"#
            }
            Self::Drag => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"source":{"type":"object","properties":{"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string","minLength":1}},"required":["snapshot_revision","element_ref"]},"target":{"type":"object","properties":{"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string","minLength":1}},"required":["snapshot_revision","element_ref"]},"include_snapshot":{"type":"boolean"}},"required":["source","target"]}"#
            }
            Self::FillForm => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"fields":{"type":"array","items":{"type":"object","properties":{"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string","minLength":1},"value":{"anyOf":[{"type":"string"},{"type":"number"},{"type":"boolean"},{"type":"array","items":{"type":["string","number"]}}]},"replace":{"type":"boolean"}},"required":["snapshot_revision","element_ref","value"]},"minItems":1},"include_snapshot":{"type":"boolean"}},"required":["fields"]}"#
            }
            Self::Dialog => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["list","clear","accept","dismiss"]},"prompt_text":{"type":"string"}},"required":["action"]}"#
            }
            Self::UploadFile => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"snapshot_revision":{"type":"integer","minimum":1},"element_ref":{"type":"string"},"file_path":{"type":"string"},"file_paths":{"type":"array","items":{"type":"string"},"minItems":1,"maxItems":20},"include_snapshot":{"type":"boolean"}},"required":["snapshot_revision","element_ref"],"anyOf":[{"required":["file_path"]},{"required":["file_paths"]}]}"#
            }
            Self::ClickAt => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"x":{"type":"number"},"y":{"type":"number"},"double_click":{"type":"boolean"},"include_snapshot":{"type":"boolean"}},"required":["x","y"]}"#
            }
            Self::Evaluate => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"expression":{"type":"string","minLength":1,"maxLength":100000}},"required":["expression"]}"#
            }
            Self::Console => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["list","get","clear"]},"message_id":{"type":"integer","minimum":1},"levels":{"type":"array","items":{"type":"string"}},"page_size":{"type":"integer","minimum":1,"maximum":500}},"required":["action"]}"#
            }
            Self::Network => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["list","get","failed","clear"]},"request_id":{"type":["string","integer"],"description":"Network.requestId；可传字符串或数字"},"resource_types":{"type":"array","items":{"type":"string"}},"page_size":{"type":"integer","minimum":1,"maximum":500},"include_body":{"type":"boolean"}},"required":["action"]}"#
            }
            Self::Emulate => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["set_user_agent","set_geolocation","clear_geolocation","set_color_scheme","set_cpu_throttling","set_network_conditions","set_headers","clear"],"description":"可选的原子仿真操作；省略时按传入的批量字段应用。"},"network_conditions":{"type":"string","enum":["offline","slow 3g","fast 3g","slow 4g","fast 4g"]},"cpu_throttling_rate":{"type":"number","minimum":1,"maximum":20},"geolocation":{"type":["object","null"]},"user_agent":{"type":["string","null"]},"accept_language":{"type":"string"},"platform":{"type":"string"},"color_scheme":{"type":"string","enum":["dark","light","auto"]},"scheme":{"type":"string","enum":["dark","light"]},"rate":{"type":"number","minimum":1,"maximum":20},"latitude":{"type":"number"},"longitude":{"type":"number"},"accuracy":{"type":"number","minimum":0},"offline":{"type":"boolean"},"latency":{"type":"number","minimum":0},"download_throughput":{"type":"number","minimum":-1},"upload_throughput":{"type":"number","minimum":-1},"headers":{"type":"object"},"extra_http_headers":{"type":["object","null"]}},"required":[]}"#
            }
            Self::Performance => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["start","stop","metrics","analyze","profile_start","profile_stop","coverage_start","coverage_take","coverage_stop"]},"include_events":{"type":"boolean","description":"analyze 时是否同时返回原始追踪事件"}},"required":["action"]}"#
            }
            Self::Lighthouse => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"mode":{"type":"string","enum":["navigation","snapshot"]},"device":{"type":"string","enum":["desktop","mobile"]},"output_dir_path":{"type":"string"}},"required":[]}"#
            }
            Self::Heap => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["usage","take_snapshot","close_snapshot","compare_snapshots","summary","details","class_nodes","dominators","duplicate_strings","edges","object_details","retainers","retaining_paths"]},"class_id":{"type":"integer","minimum":0},"class_name":{"type":"string"},"node_id":{"type":"integer","minimum":0},"page_index":{"type":"integer","minimum":0},"page_size":{"type":"integer","minimum":1,"maximum":500},"max_depth":{"type":"integer","minimum":1,"maximum":64}},"required":["action"]}"#
            }
            Self::ThirdParty => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["list","clear"]}},"required":["action"]}"#
            }
            Self::WebMcp => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["list","execute"]},"tool_name":{"type":"string"},"input":{"type":"object"}},"required":["action"]}"#
            }
            Self::Pwa => {
                r#"{"type":"object","properties":{"tab_id":{"type":"string"},"action":{"type":"string","enum":["state"]}},"required":["action"]}"#
            }
        }
    }

    pub fn input_schema(self) -> serde_json::Value {
        serde_json::from_str(self.input_schema_json())
            .expect("generated browser tool input schema must be valid JSON")
    }

    pub fn is_supported(self) -> bool {
        Self::ALL.contains(&self)
    }
}
