// @generated by scripts/generate-app-server-protocol.mjs from contracts/app-server/app-server.schema.json.
// DO NOT EDIT. Change the schema and rerun: npm run protocol:generate

export const PROTOCOL_NAME = "magi.app-server" as const;
export const PROTOCOL_MAJOR = 1 as const;
export const PROTOCOL_MINOR = 0 as const;
export const JSONRPC_VERSION = "2.0" as const;
export const APP_SERVER_METHODS = ["initialize","initialized","ping","session/list","session/read","turn/start","events/subscribe","browser/tools/list","browser/tool","approval/request","$/cancelRequest"] as const;

export type AppServerRequestMethod = "initialize" | "ping" | "session/list" | "session/read" | "turn/start" | "events/subscribe" | "browser/tools/list" | "browser/tool" | "approval/request";
export type AppServerNotificationMethod = "initialized" | "$/cancelRequest";
export type AppServerMethod = AppServerRequestMethod | AppServerNotificationMethod;

export interface AppServerMethodParams {
  initialize: InitializeParams;
  initialized: EmptyParams;
  ping: EmptyParams;
  "session/list": SessionListParams;
  "session/read": SessionReadParams;
  "turn/start": TurnStartParams;
  "events/subscribe": EventSubscribeParams;
  "browser/tools/list": BrowserToolsListParams;
  "browser/tool": BrowserToolParams;
  "approval/request": ApprovalRequestParams;
  "$/cancelRequest": CancelRequestParams;
}

export interface AppServerMethodResults {
  initialize: InitializeResult;
  ping: PingResult;
  "session/list": SessionListResult;
  "session/read": SessionReadResult;
  "turn/start": TurnStartResult;
  "events/subscribe": EventSubscribeResult;
  "browser/tools/list": BrowserToolsListResult;
  "browser/tool": BrowserToolResult;
  "approval/request": ApprovalDecision;
}

export type AppServerRequestParams<M extends AppServerRequestMethod> = AppServerMethodParams[M];
export type AppServerRequestResult<M extends AppServerRequestMethod> = AppServerMethodResults[M];
export type AppServerNotificationParams<M extends AppServerNotificationMethod> = AppServerMethodParams[M];

export interface AppServerMethodSignature {
  kind: "request" | "notification";
  params: string;
  result?: string;
  serverRequest?: boolean;
}

export const APP_SERVER_METHOD_SIGNATURES = {
  "initialize": {
    kind: "request",
    params: "InitializeParams",
    result: "InitializeResult"
  },
  "initialized": {
    kind: "notification",
    params: "EmptyParams"
  },
  "ping": {
    kind: "request",
    params: "EmptyParams",
    result: "PingResult"
  },
  "session/list": {
    kind: "request",
    params: "SessionListParams",
    result: "SessionListResult"
  },
  "session/read": {
    kind: "request",
    params: "SessionReadParams",
    result: "SessionReadResult"
  },
  "turn/start": {
    kind: "request",
    params: "TurnStartParams",
    result: "TurnStartResult"
  },
  "events/subscribe": {
    kind: "request",
    params: "EventSubscribeParams",
    result: "EventSubscribeResult"
  },
  "browser/tools/list": {
    kind: "request",
    params: "BrowserToolsListParams",
    result: "BrowserToolsListResult"
  },
  "browser/tool": {
    kind: "request",
    params: "BrowserToolParams",
    result: "BrowserToolResult"
  },
  "approval/request": {
    kind: "request",
    params: "ApprovalRequestParams",
    result: "ApprovalDecision",
    serverRequest: true
  },
  "$/cancelRequest": {
    kind: "notification",
    params: "CancelRequestParams"
  }
} as const;

export type JsonRpcVersion = "2.0";

export type JsonRpcRequestId = string | number;

export type JsonValue = unknown;

export interface ProtocolVersion {
  major: number;
  minor: number;
}

export interface ClientInfo {
  name: string;
  title?: string | null;
  version?: string | null;
}

export interface ClientCapabilities {
  desktopBrowserSurface?: boolean;
  browserTools?: boolean;
  approvals?: boolean;
  streaming?: boolean;
  optOutNotificationMethods?: Array<string>;
}

export interface EmptyParams {
}

export interface PingResult {
  runtimeEpoch: string;
}

export interface ServerCapabilities {
  sessions: boolean;
  turns: boolean;
  events: boolean;
  approvals: boolean;
  browserTools: boolean;
}

export interface InitializeParams {
  clientInfo: ClientInfo;
  protocol?: ProtocolVersion | null;
  capabilities?: ClientCapabilities;
}

export interface InitializeResult {
  serverInfo: ClientInfo;
  protocol: ProtocolVersion;
  runtimeEpoch: string;
  capabilities: ServerCapabilities;
}

export interface BrowserToolsListParams {
  sessionId?: string | null;
}

export interface EventSubscribeParams {
  sessionId?: string | null;
  workspaceId?: string | null;
  afterSequence?: number | null;
}

export interface SessionListParams {
  workspaceId?: string | null;
}

export interface SessionReadParams {
  sessionId: string;
  includeTurns?: boolean;
}

export type SessionScope = "personal" | "workspace";

export interface SessionTurnImage {
  name: string;
  dataUrl: string;
}

export type SessionContextReferenceKind = "file" | "directory";

export interface SessionContextReference {
  kind: SessionContextReferenceKind;
  path: string;
  pathRef?: string | null;
  name: string;
}

export type AccessProfile = "read_only" | "restricted" | "full_access";

export interface TurnStartParams {
  sessionId?: string | null;
  scope: SessionScope;
  workspaceId?: string | null;
  workspacePath?: string | null;
  text?: string | null;
  skillName?: string | null;
  locale?: string | null;
  goalMode?: boolean;
  images?: Array<SessionTurnImage>;
  contextReferences?: Array<SessionContextReference>;
  browserAnnotationRefs?: Array<string>;
  accessProfile?: AccessProfile | null;
  orchestratorSessionConfig?: JsonValue | null;
  requestId?: string | null;
  userMessageId?: string | null;
  placeholderMessageId?: string | null;
  steerCurrentTurn?: boolean;
  expectedTurnId?: string | null;
  replaceTurnId?: string | null;
}

export interface SessionSummary {
  sessionId: string;
  workspaceId: string | null;
  title: string;
  status: string;
  createdAt: number;
  updatedAt: number;
  messageCount: number;
  isRunning: boolean;
  runningTaskCount: number;
  hasUnreadCompletion: boolean;
}

export interface SessionListResult {
  sessions: Array<SessionSummary>;
  runtimeEpoch: string;
}

export interface SessionReadResult {
  session: SessionSummary;
  turns: Array<CanonicalTurn>;
  runtimeEpoch: string;
}

export type EventCategory = "Domain" | "Audit" | "Usage" | "Projection" | "System";

export type CanonicalTurnStatus = "pending" | "running" | "completed" | "blocked" | "failed" | "interrupted" | "cancelled" | "superseded";

export type CanonicalTurnItemKind = "user_message" | "assistant_text" | "assistant_thinking" | "tool_call" | "task_status" | "system_notice";

export type CanonicalTurnItemStatus = "pending" | "running" | "completed" | "blocked" | "failed" | "cancelled";

export type CanonicalTurnEventKind = "turn_started" | "turn_item_upsert" | "turn_completed" | "turn_superseded";

export interface CanonicalTurnVisibility {
  renderable?: boolean;
}

export interface CanonicalToolCall {
  callId: string;
  name: string;
  arguments?: JsonValue | null;
  result?: JsonValue | null;
  error?: string | null;
}

export interface CanonicalWorkerRef {
  taskId?: string | null;
  workerId?: string | null;
  roleId?: string | null;
  title?: string | null;
}

export interface CanonicalTurnItem {
  sessionId: string;
  turnId: string;
  turnSeq: number;
  itemId: string;
  itemSeq: number;
  kind: CanonicalTurnItemKind;
  createdAt: number;
  status: CanonicalTurnItemStatus;
  itemVersion?: number | null;
  updatedAt: number;
  title?: string | null;
  content?: string | null;
  blocks?: Array<unknown>;
  tool?: CanonicalToolCall | null;
  worker?: CanonicalWorkerRef | null;
  sourceThreadId: string;
  visibility: CanonicalTurnVisibility;
  metadata?: Record<string, JsonValue>;
}

export interface CanonicalTurn {
  sessionId: string;
  turnId: string;
  turnSeq: number;
  acceptedAt: number;
  completedAt?: number | null;
  status: CanonicalTurnStatus;
  responseDurationMs?: number | null;
  usage?: JsonValue | null;
  items: Array<CanonicalTurnItem>;
  metadata?: Record<string, JsonValue>;
}

export interface CanonicalTurnEvent {
  canonicalSchemaVersion: string;
  canonicalEventKind: CanonicalTurnEventKind;
  canonicalTurn?: CanonicalTurn | null;
  canonicalItem?: CanonicalTurnItem | null;
}

export type TurnStartKind = "accepted" | "queued";

export type TurnStartRoute = "chat" | "execute" | "task" | "continue" | "steer";

export interface TurnQueueInfo {
  queueId: string;
  queuePosition: number;
}

export interface TurnStartResult {
  kind: TurnStartKind;
  replayed: boolean;
  requestId: string | null;
  sessionId: string;
  turnId: string | null;
  entryId: string;
  eventId: string;
  acceptedAt: number;
  runtimeEpoch: string;
  eventStreamNextSequence: number;
  createdSession: boolean;
  route: TurnStartRoute | null;
  sessionSummary: SessionSummary | null;
  userMessageItemId: string | null;
  canonicalTurn: CanonicalTurn | null;
  canonicalItem: CanonicalTurnItem | null;
  queue: TurnQueueInfo | null;
  rootTaskId?: string | null;
  actionTaskId?: string | null;
  executionChainRef?: string | null;
  steeredTurnId?: string | null;
  canonicalSchemaVersion?: string | null;
  canonicalEventKind?: string | null;
}

export interface EventEnvelope {
  event_id: string;
  event_type: string;
  category: EventCategory;
  occurred_at: number;
  sequence: number;
  workspace_id?: string | null;
  session_id?: string | null;
  mission_id?: string | null;
  assignment_id?: string | null;
  task_id?: string | null;
  payload: Record<string, JsonValue>;
}

export interface EventStreamSnapshot {
  next_sequence: number;
  recent_events: Array<EventEnvelope>;
}

export interface EventNotificationParams {
  sequence: number;
  event: EventEnvelope;
}

export interface EventSubscribeResult {
  subscribed: boolean;
  nextSequence: number;
  resyncRequired: boolean;
}

export interface EventSnapshotParams {
  nextSequence: number;
  recentEvents: Array<EventEnvelope>;
}

export type EventResyncReason = "afterSequenceExpired" | "clientTooSlow";

export interface EventResyncRequiredParams {
  reason: EventResyncReason;
  requestedAfterSequence: number | null;
  skipped: number | null;
  snapshot: EventStreamSnapshot;
}

export type BrowserAccessProfile = "read_only" | "restricted" | "full_access";

export type BrowserToolAccess = "read" | "write" | "mixed";

export interface BrowserToolDescriptor {
  name: string;
  access: BrowserToolAccess;
}

export type BrowserHostStatus = "stopped" | "starting" | "ready" | "reconnecting" | "failed";

export interface BrowserCapabilitySnapshot {
  revision: number;
  inAppBrowserEnabled: boolean;
  browserUseEnabled: boolean;
  hostStatus: BrowserHostStatus;
  hostProtocolCompatible: boolean;
  accessProfile: BrowserAccessProfile;
}

export interface BrowserToolsListResult {
  tools: Array<BrowserToolDescriptor>;
  capabilities: BrowserCapabilitySnapshot;
  runtimeEpoch: string;
}

export type BrowserToolResultStatus = "completed" | "blocked" | "failed" | "cancelled" | "indeterminate";

export interface BrowserToolResult {
  tool: string;
  status: BrowserToolResultStatus;
  payload: JsonValue;
  itemId: string;
  turnId: string;
  runtimeEpoch: string;
}

export interface BrowserToolParams {
  sessionId: string;
  tool: string;
  arguments: Record<string, JsonValue>;
  workspaceId?: string | null;
  callId?: string | null;
  accessProfile?: BrowserAccessProfile;
  browserCapabilityRevision?: number | null;
  browserExecutionId?: string | null;
  taskId?: string | null;
  workerId?: string | null;
}

export interface ApprovalRequestParams {
  sessionId: string;
  reason: string;
  risk?: string | null;
}

export interface ApprovalDecision {
  approved: boolean;
}

export interface JsonRpcError {
  code: number;
  message: string;
  data?: JsonValue;
  retryable?: boolean;
}

export interface JsonRpcRequest {
  jsonrpc: JsonRpcVersion;
  id: JsonRpcRequestId;
  method: string;
  requestTimeoutMs?: number | null;
  params?: JsonValue;
}

export interface JsonRpcNotification {
  jsonrpc: JsonRpcVersion;
  method: string;
  requestTimeoutMs?: number | null;
  params?: JsonValue;
}

export interface JsonRpcResultResponse {
  jsonrpc: JsonRpcVersion;
  id: JsonRpcRequestId;
  result: JsonValue;
}

export interface JsonRpcErrorResponse {
  jsonrpc: JsonRpcVersion;
  id: JsonRpcRequestId;
  error: JsonRpcError;
}

export interface JsonRpcResponse {
  jsonrpc: JsonRpcVersion;
  id: JsonRpcRequestId;
  result?: JsonValue;
  error?: JsonRpcError;
}

export type CancelMethod = "$/cancelRequest";

export interface CancelRequestParams {
  id: JsonRpcRequestId;
}

export interface CancelNotification {
  jsonrpc: JsonRpcVersion;
  method: CancelMethod;
  params: CancelRequestParams;
}

export type JsonRpcServerRequest = JsonRpcRequest;

export type JsonRpcServerNotification = JsonRpcNotification;

export type JsonRpcServerResponse = JsonRpcResponse;

export type ClientRequest = JsonRpcRequest;

export type ClientNotification = JsonRpcNotification;

export type ClientResponse = JsonRpcResponse;

export type ServerRequest = JsonRpcServerRequest;

export type ServerNotification = JsonRpcServerNotification;

export type ServerResponse = JsonRpcServerResponse;

export type JsonRpcMessage = JsonRpcRequest | JsonRpcNotification | JsonRpcResponse;
