[package]
name = "magi-web-model"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
sha2.workspace = true
tokio = { workspace = true }
tracing.workspace = true
magi-bridge-client = { path = "../magi-bridge-client" }
magi-process = { path = "../magi-process" }
