// @generated by scripts/generate-browser-network-policy.mjs from contracts/desktop-browser/network-policy.json.
// DO NOT EDIT. Change the source and rerun: npm run browser-network-policy:generate

export const BROWSER_BLOCKED_HOSTNAMES: readonly string[] = [
  "metadata.google.internal",
  "metadata.goog",
  "instance-data.ec2.internal",
];

export const BROWSER_BLOCKED_CIDRS: readonly string[] = [
  "169.254.0.0/16",
  "100.100.100.200/32",
  "192.0.0.192/32",
  "fd00:ec2::254/128",
  "fe80::/10",
];

export const BROWSER_LOOPBACK_HOSTNAMES: readonly string[] = [
  "localhost",
];

export const BROWSER_LOOPBACK_CIDRS: readonly string[] = [
  "127.0.0.0/8",
  "0.0.0.0/8",
  "::1/128",
  "::/128",
];

export const BROWSER_PRIVATE_NETWORK_CIDRS: readonly string[] = [
  "10.0.0.0/8",
  "172.16.0.0/12",
  "192.168.0.0/16",
  "100.64.0.0/10",
  "fc00::/7",
];

export const BROWSER_PREVIEW_HOSTNAME = "site.localhost";

export const BROWSER_PREVIEW_PATH_PREFIX = "/api/files/site/";

export const BROWSER_PREVIEW_OPEN_PATH = "/api/files/site-open";
